services:
  - type: web
    name: tlyt-bot
    env: node
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y python3-pip ffmpeg
      pip3 install yt-dlp
      npm install
    startCommand: node bot.js
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
